mysql:
  domain: analytics.db.svc.eqiad.wmflabs
  # TODO: remove this when the multiinstance replica proxy is removed
  host: enwiki.analytics.db.svc.eqiad.wmflabs
dbProxy: 
  image:
    tag: latest
jupyterhub:
  hub:
    extraVolumes:
    - name: homes
      nfs:
        server: nfs-tools-project.svc.eqiad.wmnet
        path: /srv/misc/shared/paws/project
    - name: dumps
      nfs:
        server: labstore1007.wikimedia.org
        path: /
    # Without this, dumps becomes inaccessible and can hang the host
    - name: dumps-src1
      nfs:
        server: labstore1007.wikimedia.org
        path: /
    - name: dumps-src2
      nfs:
        server: labstore1006.wikimedia.org
        path: /
    extraConfig:
      00-myConfig: |
          localdev = False
    db:
      type: mysql
      upgrade: true
  ingress: 
    enabled: true
    hosts:
    - hub.paws.wmcloud.org
  singleuser:
    extraEnv:
      HUB_DOMAIN: "hub.paws.wmcloud.org"  # Check jupyterhub.ingress.hosts
# So that we don't use the Bitnami charts in Cloud VPS deployment
localdev:
  enabled: false
